### ISSUE TITLE
GetDeployedCodePackageListAsync throws MissingMethodException

### ISSUE THREAD

**Issue by MatanShabtay** [microsoft/service-fabric#1001]
Service Fabric Runtime Version: 
7.1.417.9590 

Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
Azure

Description: 
When calling GetDeployedCodePackageListAsync through a stateless service, I get the following runtime exception
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Fabric.Query.DeployedCodePackageList> QueryClient.GetDeployedCodePackageListAsync(System.String, System.Uri, System.String, System.String)'.

I am using the following NuGet versions:
Microsoft.ServiceFabric.Services Version=4.0.470
Microsoft.ServiceFabric Version=7.0.470
Microsoft.ServiceFabric.Data" Version=4.0.470

Observed behavior:
MissingMethodException is thrown when calling the method

Expected Behavior:
The method should work

OS(Windows/Linux): 
Windows
---
Assignees: @microsoft/service-fabric-triage

**Comment by gkhanna79** [comment]
@aryamsft Can you please confirm that this is the API surface gap that was fixed for 7.1?

@shsha-msft FYI

**Comment by aryamsft** [comment]
@MatanShabtay @gkhanna79 Yes this issue has been in SF7.2

**Comment by MatanShabtay** [comment]
So when SF 7.1CU2 will be available in all Azure clouds? (Public, FFX, MCK)?
I just checked and version 7.1.428.9590 (SF7.1CU2) is still not available in public cloud, I assume it's the same situation in sovereign clouds,

**Comment by gkhanna79** [comment]
@MatanShabtay We are still working on the release schedule and will update this when we have concrete details on it.

@athinanthny FYI.

**Comment by MatanShabtay** [comment]
Thanks. Also please let me know if there is a workaround I can use on the meantime. Its blocking me from deploying a crucial service on our production clusters.

**Comment by aryamsft** [comment]
The new API adds a boolean to the signature (old API will work the same once 7.1CU2 is out).  You can add "false" as to the new boolean value and recompile your app.

**Comment by MatanShabtay** [comment]
Thanks. I eventually ended updating the SDK too, as the boolean parameter includeCodePackageUsageStats doesnt exist in the version mentioned above
